# Generated by Django 2.1.1 on 2018-09-06 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='name',
            new_name='name_user',
        ),
    ]
