# Generated by Django 2.1.1 on 2018-09-06 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20180906_1919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='email',
            new_name='email_user',
        ),
    ]
