# Generated by Django 2.1.1 on 2018-09-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_productbasket'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbasket',
            name='session_key',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
