# Generated by Django 2.1.1 on 2018-09-21 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_productbasket_session_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productbasket',
            old_name='product',
            new_name='productTest',
        ),
    ]
