# Generated by Django 2.1.1 on 2018-09-21 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20180921_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productbasket',
            old_name='productTest',
            new_name='product',
        ),
    ]
