# Generated by Django 2.1.1 on 2018-09-21 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20180921_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbasket',
            name='product',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
